### ISSUE TITLE
_directoryCallbacks not always called

### ISSUE THREAD

**Issue by jesperstarkar** [evs-broadcast/node-emberplus#7]
I haven't gotten totally control of this behaviour yet – then I would have patched it myself.

The idea of directoryCallbacks is somewhat strange to me. It works for some nodes, but not all. I have stepped and traced a far bit, but I'm out of clue/energy to solve it, so I'm leaving an issue here to revisit this topic or inspire others to have a look.

**Comment by alhasha001** [comment]
hi, i have a question for you. were you able to get the node/nodes without the EmberPlusViewer or any other ember+ viewer program ?
Thanks

**Comment by WolfgangVonL** [comment]
I also encountered this issue with getNodeByPath method. 

I was trying to get a node with this path **_device/Output/Output 1/_**
**_getNodeByPath_** retrieved correctly the  first node **_device_** informations but then it's unable to get this node elements due to _directoryCallbacks not fired. 

This issue breaks the recursive loop, stop right after the first node and a TimeOut error is fired.

I create my own function which use getDirectory() recursively to obtain a specific node from a path.

Do you have any idea on that issue ?

**Comment by dufourgilles** [comment]
I was able to reproduce and created a test on it.
Problem was with QualifiedNode.
I pushed a fix in .25

**Comment by WolfgangVonL** [comment]
Thank you very much but sadly I still have some new issue...

I just pulled the last version and test it with my code. The loop still breaks but this time on level 3 of the path I provided with "invalid path" error. The ### **getNodeByPath** method is unable to get the children of the level 3 path despite the fact that this node is a QualifierNode and have children. I'm working with a ember tree file (which contains all the required nodes) served with TreeServer. I'll test my code with the real device.

There is a also small typo in the package.json: line 33 a comma is missin.

**Comment by WolfgangVonL** [comment]
Hi Gilles,

I've run few tests:

1- ember file from my device served with node-emberplus server
2- embrionix ember file included in the repo:
`tree.getNodeByPath('Device/Transmitters/Group 1/Group SDP A').then(function(node){
        
    }).catch(function(err){
       
    })`
3- directly connected to my device

In the three cases, I've the same behavior: **_from third level if the node is QualifierNode, getNodeByPath is unable to get his children_**. So it breaks the child.getElement(path[0]) function and throws an error "invalid path".

I don't understand 

Thanks for your help

**Comment by dufourgilles** [comment]
Thanks for your help.
I got it reproduced.  Actually the callback was called many times for error and last time with success.  As I ignored the error in my test, I did not see it.
I pushed a new fix.
Please try it.
BTW, I added a 2nd parameter to getNodeByPath which is a timeout in seconds (default 2).

**Comment by WolfgangVonL** [comment]
I just tried with the my device ember file and with the embrionix file.

Like yesterday if I request this path **_Device/Transmitters/Group 1_**, everything works fine.

But when I try to request this one **_Device/Transmitters/Group 1/Group SDP A_**, I still have an error: it's not the "invalid path" error anymore but a timeout error:

`{ EmberTimeoutError: Request 0 timed out
    at DeviceTree.timeoutRequest (/node_modules/node-emberplus/device.js:291:24)
    at Timeout.self.timeout.setTimeout (/node_modules/node-emberplus/device.js:254:22)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'EmberTimeoutError', message: 'Request 0 timed out' }` 

I've tried to increment the timeout value to 10, same thing...

Hope it'll help you to figure out the issue.

**Comment by jesperstarkar** [comment]
Can you please test paths that don't contain spaces in the names?

**Comment by WolfgangVonL** [comment]
On the device I'm connecting to, except in the first level, all the names contain spaces.
In embrionix tree, the only paths with no space are **_Device/Management/[parameter name]_**. 
 And with this kind of paths with (3 levels), I never have the problem.
